[build]
builder = "nixpacks"
nixpacksPlan = "nixpacks.toml"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 600"
healthcheckPath = "/login"
restartPolicyType = "on_failure"
